<?php


/**
 * Skeleton subclass for performing query and update operations on the 'firm' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Apr 16 18:05:12 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class FirmPeer extends BaseFirmPeer {

} // FirmPeer
