<?php


/**
 * Skeleton subclass for representing a row from the 'interest' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat May 14 16:42:58 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Interest extends BaseInterest
{
	public function __toString()
	{
		return $this->getName();
	}
} // Interest
