<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2011/04/16 18:05:13
return array(

  // sfMinaclPropelPlugin_module_libs

  // sfMinaclPropelPlugin_lib
  'sfminaclpropelformgenerator' => '/home/rob/test-symfony/plugins/sfMinaclPropelPlugin/lib/generator/sfMinaclPropelFormGenerator.php',
  'sfminaclbuildformstask' => '/home/rob/test-symfony/plugins/sfMinaclPropelPlugin/lib/task/sfMinaclBuildFormsTask.class.php',

  // sfMinaclPlugin_module_libs

  // sfMinaclPlugin_lib
  'sfformminacl' => '/home/rob/test-symfony/plugins/sfMinaclPlugin/lib/sfFormMinacl.php',

  // sfPropelPlugin_module_libs

  // sfPropelPlugin_lib
  'sfpropeldatabase' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/database/sfPropelDatabase.class.php',
  'sfvalidatorpropelchoice' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelChoice.class.php',
  'sfvalidatorpropelunique' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelUnique.class.php',
  'sfpropelbehavior' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/addon/sfPropelBehavior.class.php',
  'sfpropelmanytomany' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/addon/sfPropelManyToMany.class.php',
  'sfmixer' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/addon/sfMixer.class.php',
  'sfpropelpager' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/addon/sfPropelPager.class.php',
  'sfpropeldatabaseschema' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/addon/sfPropelDatabaseSchema.class.php',
  'sfpropeldata' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/addon/sfPropelData.class.php',
  'sfpropel' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/addon/sfPropel.class.php',
  'sftesterpropel' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/test/sfTesterPropel.class.php',
  'sfpropelbehaviori18n' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18n.php',
  'sfpropelbehaviortimestampable' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorTimestampable.php',
  'sfpropelbehaviori18ntranslation' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18nTranslation.php',
  'sfpropelbehaviorsymfonybehaviors' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfonyBehaviors.php',
  'sfpropelbehaviorbase' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorBase.php',
  'sfpropelbehaviorsymfony' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfony.php',
  'swift_propelspool' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/mailer/Swift_PropelSpool.class.php',
  'sfformpropel' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/form/sfFormPropel.class.php',
  'sfformfilterpropel' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/form/sfFormFilterPropel.class.php',
  'sfpropelroute' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/routing/sfPropelRoute.class.php',
  'sfpropelroutecollection' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/routing/sfPropelRouteCollection.class.php',
  'sfpropelformgenerator' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/generator/sfPropelFormGenerator.class.php',
  'sfpropelgenerator' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/generator/sfPropelGenerator.class.php',
  'sfpropelformfiltergenerator' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/generator/sfPropelFormFilterGenerator.class.php',
  'sfwidgetformpropelchoice' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelChoice.class.php',
  'sfpropellogger' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/log/sfPropelLogger.class.php',
  'sfwebdebugpanelpropel' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/debug/sfWebDebugPanelPropel.class.php',
  'sfpropeldatadumptask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelDataDumpTask.class.php',
  'sfpropelinsertsqltask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelInsertSqlTask.class.php',
  'sfpropelbuildmodeltask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildModelTask.class.php',
  'sfpropelbuildformstask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildFormsTask.class.php',
  'sfphinglistener' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPhingListener.php',
  'sfpropelgeneratemoduletask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleTask.class.php',
  'sfpropelgraphviztask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelGraphvizTask.class.php',
  'sfpropeldataloadtask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelDataLoadTask.class.php',
  'sfpropelgeneratemoduleforroutetask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleForRouteTask.class.php',
  'sfpropelbuildfilterstask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildFiltersTask.class.php',
  'sfpropelbuildallloadtask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllLoadTask.class.php',
  'sfpropelbuildsqltask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildSqlTask.class.php',
  'sfpropelbasetask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBaseTask.class.php',
  'sfpropelbuildalltask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllTask.class.php',
  'sfphing' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPhing.class.php',
  'sfpropelschematoxmltask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToXmlTask.class.php',
  'sfpropelbuildtask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildTask.class.php',
  'sfpropelschematoymltask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToYmlTask.class.php',
  'sfpropelbuildschematask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildSchemaTask.class.php',
  'sfpropelgenerateadmintask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelGenerateAdminTask.class.php',
  'sfpropelconfiguredatabasetask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelConfigureDatabaseTask.class.php',

  // project
  'baseform' => '/home/rob/test-symfony/lib/form/BaseForm.class.php',
  'baseuserform' => '/home/rob/test-symfony/lib/form/minacl/base/BaseUserForm.class.php',
  'basefirmform' => '/home/rob/test-symfony/lib/form/minacl/base/BaseFirmForm.class.php',

  // project_model
  'userpeer' => '/home/rob/test-symfony/lib/model/UserPeer.php',
  'firmtablemap' => '/home/rob/test-symfony/lib/model/map/FirmTableMap.php',
  'usertablemap' => '/home/rob/test-symfony/lib/model/map/UserTableMap.php',
  'baseuserpeer' => '/home/rob/test-symfony/lib/model/om/BaseUserPeer.php',
  'basefirm' => '/home/rob/test-symfony/lib/model/om/BaseFirm.php',
  'basefirmpeer' => '/home/rob/test-symfony/lib/model/om/BaseFirmPeer.php',
  'baseuser' => '/home/rob/test-symfony/lib/model/om/BaseUser.php',
  'user' => '/home/rob/test-symfony/lib/model/User.php',
  'firm' => '/home/rob/test-symfony/lib/model/Firm.php',
  'firmpeer' => '/home/rob/test-symfony/lib/model/FirmPeer.php',

  // application
  'myuser' => '/home/rob/test-symfony/apps/frontend/lib/myUser.class.php',

  // modules
);
